### ISSUE TITLE
This is doing string comparisons, not numbers, for the prices

### ISSUE THREAD

**Issue by subos2008** [tony-ho/binance-oco#10]
This is doing string comparisons, not numbers, for the prices.

The functions to adjust the input prices return strings. So comparing a price of 56 vs 87 would work. But comparing 100 vs 56 would think that 56 is bigger because it compares the strings and not their numeric values.

I've fixed this and done some other work on my fork. Note my fork is not well tested so use it at your own risk.

I dont have time to make a pull request at the moment Tony, but many thanks for releasing this code!

**Comment by tony-ho** [comment]
@subos2008 Thanks for raising this issue.

I have been able to reproduce with a test case and have added [bignumber.js](https://github.com/MikeMcl/bignumber.js) for price/amount calculations in [v2.3.0](https://github.com/tony-ho/binance-oco/releases/tag/v2.3.0).
