### ISSUE TITLE
how to do this ?

### ISSUE THREAD

**Issue by happmaoo** [tony-ho/binance-oco#11]
say I have 1 btc now the price is 15000 and set a sell order at 20000 usdt.when price hit 20000 sell it at 19500. and when price down to 14500 cancel the sell order and set a limit sell at 14000.
so it is more risk-less, can you do this?

**Comment by tony-ho** [comment]
@happmaoo Thanks for your question.

binance-oco won't be able to set a target sell order at 19500 when the price reaches 20000 as:
-  doesn't support separate trigger and limit prices for target sell orders, and
- Binance won't allow you to place a STOP-LIMIT sell order at a higher price than the current price; it will return an "Order would trigger immediately" error.

It does support separate stop and limit prices for the stop loss using the `-l` option. See https://github.com/tony-ho/binance-oco#stop-limit-and-limit-sell-orders for further details.

To have it monitor with a target limit sell at 20000 and a stop limit sell down to 14000 if the price reaches 14500, use:

```
binance-oco -p BTCUSDT -a 1 -s 14500 -l 14000 -t 20000
```

Note that the stop order is always placed first to protect your position. It is only cancelled, and the target order set, once the target price has been reached.
