### ISSUE TITLE
waitForSellOrderFill(...).finally is not a function

### ISSUE THREAD

**Issue by Jorijn** [tony-ho/binance-oco#12]
Hi,

I've been trying to play around with binance-oco but I'm receiving an error:

```
jorijn@x:~$ binance-oco -p BNBUSDT -a 0.5 -s 26.6 -t 26.9
  binance-oco Validating stop order: { symbol: 'BNBUSDT', side: 'SELL', quantity: '0.50', price: '20.0001', stopPrice: '26.6000', type: 'STOP_LOSS_LIMIT' } +0ms
  binance-oco Stop order valid +350ms
  binance-oco Validating target order: { symbol: 'BNBUSDT', side: 'SELL', quantity: '0.50', price: '26.9000', type: 'LIMIT' } +1ms
  binance-oco Target order valid +522ms
  binance-oco Sell response: { symbol: 'BNBUSDT', orderId: xxxxx, clientOrderId: 'xxxx', transactTime: 1564489146179, price: '20.00010000', origQty: '0.50000000', executedQty: '0.00000000', cummulativeQuoteQty: '0.00000000', status: 'NEW', timeInForce: 'GTC', type: 'STOP_LOSS_LIMIT', side: 'SELL', stopPrice: '26.60000000', fills: [] } +298ms
  binance-oco order id: 206171384 +1ms
  binance-oco waitForSellOrderFill(...).finally is not a function +0ms
```

Am I doing something wrong?

The order remained active on the exchange after the process crashed.

Also, I've read that it keeps the stop-loss order until the target price has been reached. I'd like to give a base price (e.g. buying price) and have the script check:

* if current price above buy price; then set limit sell
* if current price below buy price; then set stop-limit sell (loss)

This way the order is always placed in the order book ahead of time and will trigger in case of a quick wick. 

Is this possible?

Thanks!

Information:
```
$ binance-oco --version
2.4.1
$ node --version
v8.9.4
$ npm --version
5.6.0
```

**Comment by tony-ho** [comment]
@Jorijn Thanks for the detailed issue report.

I suspect the `.finally is not a function` error message is because you are running node 8.x. The `finally()` method is only supported in node 10.x and above:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

10.x is the current LTS release so it is recommended to update anyway:
https://nodejs.org/en/about/releases/

Regarding swapping the stop-loss vs target orders,the conditional checks for when the swaps happen are on the following lines:
https://github.com/tony-ho/binance-oco/blob/b26b000b278b760219856f25fff453ca2b695d27/src/binance-oco.ts#L208

https://github.com/tony-ho/binance-oco/blob/b26b000b278b760219856f25fff453ca2b695d27/src/binance-oco.ts#L218

**Comment by Jorijn** [comment]
Hi,

I tried running the process on my NAS, which is limited to Node 8 currently. I'll have to try and compile it by hand. 

Could you give some pointers on where to add a CLI option to include a base price? I'm familiar with JS scoping to get this data to the `waitForSellOrderFill` method.

Thanks.

**Comment by tony-ho** [comment]
CLI options can be added in `src/cli.ts`. The app uses yargs (https://yargs.js.org/) to parse arguments.

Then in `src/binance-oco.ts`, you will need to update two places with the new option:
- joi (https://github.com/hapijs/joi) schema validation
https://github.com/tony-ho/binance-oco/blob/b26b000b278b760219856f25fff453ca2b695d27/src/binance-oco.ts#L17
- the `options` object passed to the `binanceOco` function
https://github.com/tony-ho/binance-oco/blob/b26b000b278b760219856f25fff453ca2b695d27/src/binance-oco.ts#L58

**Comment by Jorijn** [comment]
Hi,

I decided against using CLI options, since it would be easier to just calculate halfway between stop-loss and take-profit and use that as a tipping point for putting the order on the books.

Would you be willing to have a look at this diff and review if this'll hold in production?

https://github.com/tony-ho/binance-oco/compare/master...Jorijn:master

Much appreciated. :-)

**Comment by tony-ho** [comment]
@Jorijn The changes look good and the tipping point is a good idea.

Just a few minor comments:
- Lines 202-3: The conditional logic defaulting `tippingPoint` to 0 if `stopPrice` and `targetPrice` isn't necessary set as this function is only called when both stop and target are set.
- Lines 205, 207: Wrapping the parameters in `new BigNumber()` isn't required as bignumber.js takes care of this.

You may also want to add test cases to increase confidence in the new behaviour. The following test cases are probably a good starting point:
https://github.com/tony-ho/binance-oco/blob/b26b000b278b760219856f25fff453ca2b695d27/__tests__/binance-oco.test.ts#L1160-L1268

**Comment by Jorijn** [comment]
Thanks Tony. I'm closing this issue!
