### ISSUE TITLE
What do you use this for?

### ISSUE THREAD

**Issue by gunar** [tony-ho/binance-oco#13]
Hi there! This looks interesting.

I'm wondering what for and how do you use binance-oco.

Like, are you trading, then use switch to the CLI for extra funcionality that Binance's GUI doesn't provide?

Thanks a bunch!

**Comment by tony-ho** [comment]
The primary use of binance-oco is to provide conditional orders for scenarios that Binance restricts eg.
- placing a sell order for an asset for which you have placed a yet to be filled buy order
- placing both a stop sell and a target sell order at the same time, as the first order ties up your available asset when an order is placed

binance-oco places the first order, then remains running and monitors the price action. It cancels and/or places additional orders as different conditions are met, eg. orders are filled (for buy then sell), or when prices are hit (for stop-loss and target sell orders).
