### ISSUE TITLE
 key error

### ISSUE THREAD

**Issue by ronanmendes** [tony-ho/binance-oco#15]
this is the content of the .env

https://imgur.com/a/oHV8kpI

but i still getting a key error:

https://imgur.com/a/FgBvCaI

many thanks for answer

**Comment by tony-ho** [comment]
Is your `.env` file in the same folder from which you are running the app ie. `C:\Users\{username}`?

**Comment by ronanmendes** [comment]
i sorry. I thought that as the code was being accept it was running everything on the bot folder so it was taking the env file in consideration.

i was running this command in another folder. When i tried running in the bot folder it worked

but i am totally confuse here with this price. I want to enter with this command at 0.0000815. Why this price of 0.0003968??? how can i enter at 0.0000815?

**Comment by tony-ho** [comment]
I suspect that you are not explicitly specifying a buy limit price. In this case, the app sets a limit price to emulate a stop market order ie. buy/sell at market price once the stop price has been hit. The behaviour is described in more detail here: https://github.com/tony-ho/binance-oco#limit-prices-for-stop-limit-orders

If you want to explicitly set the buy limit price, you need to set this using the `-B/-E` option.

**Comment by ronanmendes** [comment]
but i used the exact synstaxe you sent in your first reply just changing the coin, see

https://imgur.com/a/FgBvCaI

this:
binance-oco -p BEAMBTC -a
4 -b 0.0000784 -s 0.0000774 -t 0.0000884

so beam still below this price right now (around xxx776

this is not the correct syntaxe? Could you please tell me what is the correct sintaxe to enter exactly at 784? I dont want to just activate at 784 and set a order to enter on the pullback 783. I want to activate and enter at 784 to do not miss the trade

many thanks for yours answers.

**Comment by tony-ho** [comment]
The syntax you have is correct and will place a buy order that will enter the trade at 784.

The price that the order shows in the logs/order history is the order *limit* price (ie. not the stop/trigger price). So the order will trigger at 784 and will buy up to the limit price.

See [How to use Stop-Limit Function](https://www.binance.com/en/support/articles/115003372072) for more information on stop-limit orders and an explanation on the differences between the stop price and limit price.

By default, the app sets a high limit price to emulate a stop market order.

If you want to explicitly set a different limit price for your buy/entry order, you can set it using the `-B/-E` option.

**Comment by ronanmendes** [comment]
sorry, i tought i had uploaded the image in my second post 

i dont know it i was clear, but look at "price". 

i am a total layman in coding and my english is not so good too. So i am still confuse

do you mean i should ignore this price? with this command the bot will sen a order to enter at 784???

thanks for you patience. 


![image](https://user-images.githubusercontent.com/43094078/68520982-33b5b200-027b-11ea-8152-fb2c1cfc50a0.png)

**Comment by tony-ho** [comment]
Yes, you can ignore _Price_ in the Binance interface. The more important field is _Trigger Conditions_ - in your screenshot it shows the order will enter at 784.
