### ISSUE TITLE
put a trade bellow using the same coin

### ISSUE THREAD

**Issue by ronanmendes** [tony-ho/binance-oco#18]
lets say i have the bot running with the parameters to buy at 10000, stop at 9000 and take profit at 11000

but i believe there is another point bellow wich can be a good entry point, for example, 7000. Can i open another instance of the bot to buy at 7000 with take profit at 8000 and stop at 6000 or one instance will afect the other?

thanks in advance

**Comment by tony-ho** [comment]
@ronanmendes The app supports running multiple instances but you'll need to:
- run each instance from a different folder using a different `.env` file
- use a different set of Binance API keys for each instance

**Comment by ronanmendes** [comment]
ok, many thanks
