### ISSUE TITLE
it did not send the TP for the second trade

### ISSUE THREAD

**Issue by ronanmendes** [tony-ho/binance-oco#19]
in the image bellow you can see i tried to use the bot for 2 trades

with the first looks like everything went as planned but the second one did not send the TP order. The 
"position" was opened until now. ANd the price went way above the tp price (xxxxx218)

you can see the command i was using for both trades

https://imgur.com/a/oBdEs9T

https://imgur.com/a/7rzKEvK

EDIT: each instance in one different directory and using a different key

**Comment by tony-ho** [comment]
@ronanmendes Unfortunately there isn't enough information in the logs provided for me to work out why the target order for the second order wasn't placed.

I'll leave this open in case someone else is able to reproduce with more information.

Let me know if you encounter this issue again, and also if you are able to successfully run two instances of the app.

**Comment by tony-ho** [comment]
@ronanmendes I'm closing this issue as this scenario will no longer occur in [v3.0.0].(https://github.com/tony-ho/binance-oco/releases/tag/v3.0.0)

The separate stop/target sell orders have been replaced with single OCO order that is placed after the buy order is filled. The sell orders can then be managed through the Binance web portal.

See [How to Use OCO (One-Cancels-the-Other) Order Type](https://www.binance.com/en/support/articles/360032605831) for information on OCO orders.
