### ISSUE TITLE
Is this valid for Margin Trading? 

### ISSUE THREAD

**Issue by afanjul** [tony-ho/binance-oco#28]
Is this code valid for trading in margin account? or futures? otherwise could you add this feature using a environment variable or something ? 
thanks

**Comment by tony-ho** [comment]
@afanjul Unfortunately this won't work for margin or futures trading as those use a different Binance API.

I haven't considered adding Futures support as Binance Futures has TP/SL and Reduce orders, so there is less of a use case for a script like this when using Futures.

I don't use margin myself but will leave this issue open in case anyone else is after this functionality, or wants to add it.
