### ISSUE TITLE
Feature Request - Safe Exit to USDT after ALT/BTC trade

### ISSUE THREAD

**Issue by crlsnr** [tony-ho/binance-oco#6]
I was trying to find the comment/request section but failed so I figured I'd ask here.  With the frequent volatility of BTC trades can go upside down overnight even after a successful OCO trade if $ is left in BTC.  What do you think of adding a feature that does something like this:

- Enter an ALT/BTC trade with a S/L and target like normal
- If S/L hit:
    - Sell executes automatically to BTC (current feature)
    - Execute a market sell to USDT (***new feature***)
- If Target hit:
    - Cancel S/L (current feature)
    - Set Target sell (current feature) 
    - After target sell is filled, Execute a market sell to USDT (***new feature***)

Just a thought to avoid a scenario where your ALT/BTC trade is up 5%, but BTC drops 5% within hours and you're at a loss or breaking even.

Thanks for considering!
@tony-ho

**Comment by tony-ho** [comment]
@crlsnr Thanks for your suggestion.

My preference is to keep the main purpose of this project as providing OCO functionality on Binance. Market sell to USDT after a trade is probably a feature more suited for a trading bot.

This feature is not something I'm looking to add, but the script could be modified to do so by updating the `checkOrderFilled` callbacks for the stop and target orders:

https://github.com/tony-ho/binance-oco/blob/f1e2cdb4e7a870e2a7a0170260515bf6416b5b59/binance-oco.js#L383
https://github.com/tony-ho/binance-oco/blob/f1e2cdb4e7a870e2a7a0170260515bf6416b5b59/binance-oco.js#L387

`data` already contains the symbol and quantity, so it just needs to work out the USDT trading pair and then `binance.marketSell`.
