### ISSUE TITLE
Feature Request - Set multiple profit target

### ISSUE THREAD

**Issue by truongtamgio** [tony-ho/binance-oco#7]
Hello,
I know your tool have 'scaling out' of a position feature but it is great if we can set multiple profit target as well. Thank you :)

**Comment by tony-ho** [comment]
@truongtamgio Thanks for the feedback.

I'm unlikely to add support for multiple profit targets at this point.

The primary goal of this project is to provide a method to achieve OCO functionality on Binance.

On an exchange with OCO orders, you would use multiple orders to set multiple profit targets.  Similarly, you could achieve the result you are after by running multiple instances of binance-oco with different targets.
